version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql_bo
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "black_office"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_unicode_ci"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init_connect='SET NAMES utf8mb4;'

