spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "298191836613-1olr2vaf0kp7ekdft9nt9vktb0bdo6r5.apps.googleusercontent.com"
            client-secret: ""
            scope:
              - email
              - profile
#            redirect-uri: https://afraid-ducks-stand.loca.lt:8080/login/oauth2/code/google
#            client-name: Google